<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>a9d40e99-dda4-4380-bf76-d4e6f71cf3a9</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Discord.Net" />
        <PackageReference Include="Microsoft.AspNetCore.Hosting" />
        <PackageReference Include="Serilog.AspNetCore" />
    </ItemGroup>
</Project>
